name: Build APK (Mahdali)

on:
  workflow_dispatch:  # run manually from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: |
          sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34"
          yes | sdkmanager --licenses

      - name: Install Gradle CLI and generate wrapper
        run: |
          sudo apt-get update && sudo apt-get install -y gradle
          gradle --version
          gradle wrapper --gradle-version 8.10.2

      - name: Build Debug APK
        run: |
          chmod +x ./gradlew
          ./gradlew --no-daemon assembleDebug --stacktrace --info

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
